"""update user

Revision ID: 8292463dc5c4
Revises: cbcb7c0b4c9f
Create Date: 2023-12-22 22:22:46.728811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8292463dc5c4'
down_revision = 'cbcb7c0b4c9f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.Text(), nullable=True))
    op.create_index('user_email', 'user', ['email'], unique=True, mysql_length=255)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_email', table_name='user', mysql_length=255)
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
