"""seed

Revision ID: 09e5ebd79bfc
Revises: 8292463dc5c4
Create Date: 2023-12-22 23:11:43.464735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "09e5ebd79bfc"
down_revision = "8292463dc5c4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(
        sa.table(
            "user",
            sa.column("name", sa.String),
            sa.column("password", sa.String),
            sa.column("email", sa.String),
            sa.column("role", sa.String),
        ),
        [
            {
                "name": "admin",
                "password": "admin",
                "email": "admin@admin.com",
                "role": "admin",
            },
            {
                "name": "user",
                "password": "user",
                "email": "user@user.com",
                "role": "user",
            },
        ],
    )

    op.bulk_insert(
        sa.table(
            "movie",
            sa.column("title", sa.String),
            sa.column("description", sa.String),
            sa.column("year", sa.Integer),
            sa.column("rating", sa.Integer),
            sa.column("genre", sa.String),
        ),
        [
            {
                "title": "The Matrix",
                "description": "A computer hacker learns about the true nature of reality and his role in the war against its controllers.",
                "year": 1999,
                "rating": 8.7,
                "genre": "Action, Sci-Fi",
            },
            {
                "title": "Inception",
                "description": "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.",
                "year": 2010,
                "rating": 8.8,
                "genre": "Action, Adventure, Sci-Fi",
            },
            {
                "title": "The Shawshank Redemption",
                "description": "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
                "year": 1994,
                "rating": 9.3,
                "genre": "Drama",
            },
            {
                "title": "Pulp Fiction",
                "description": "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
                "year": 1994,
                "rating": 8.9,
                "genre": "Crime, Drama",
            },
            {
                "title": "The Dark Knight",
                "description": "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                "year": 2008,
                "rating": 9.0,
                "genre": "Action, Crime, Drama",
            },
            {
                "title": "Forrest Gump",
                "description": "The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate and other historical events unfold through the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.",
                "year": 1994,
                "rating": 8.8,
                "genre": "Drama, Romance",
            },
            {
                "title": "The Godfather",
                "description": "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
                "year": 1972,
                "rating": 9.2,
                "genre": "Crime, Drama",
            },
            {
                "title": "Interstellar",
                "description": "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
                "year": 2014,
                "rating": 8.6,
                "genre": "Adventure, Drama, Sci-Fi",
            },
            {
                "title": "The Lord of the Rings: The Return of the King",
                "description": "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
                "year": 2003,
                "rating": 8.9,
                "genre": "Action, Adventure, Drama",
            },
            {
                "title": "The Social Network",
                "description": "Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook but is later sued by two brothers who claimed he stole their idea, and the co-founder who was later squeezed out of the business.",
                "year": 2010,
                "rating": 7.7,
                "genre": "Biography, Drama",
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
